version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run build
      - run: sudo apt update && sudo apt install -y awscli
      - run: aws s3 sync --acl 'public-read' --region us-east-1 ./build/ s3://react-order-board/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
